### PR TITLE
Darshan

### PR DESCRIPTION
**Pull request by DarshanAIakhramsing**
Added factories and migrations and models for anime and categories

### CODE REVIEW

**Review by okapifan — CHANGES_REQUESTED** [review]
Make singular name for Categories

**Review by okapifan — APPROVED** [review]
Well job, but plz don't delete that fucking password resets thingy

**Review by okapifan — APPROVED** [review]
Well job Teddy bear

**Review by Kokosnootje — APPROVED** [review]
Wow, you did such a great job

**Pull request merged**
